const respondentKey = [
    {key:0, value:'select...'},
    {key:1, value:'attorney general of the United States, or his office'},
    {key:2, value:'specified state board or department of education'},
    {key:3,	value:'city, town, township, village, or borough government or governmental unit'},
    {key:4, value:'state commission, board, committee, or authority'},
    {key:5,	value:'county government or county governmental unit, except school district'},
    {key:6, value:'court or judicial district'},
    {key:7, value:'state department or agency'},
    {key:8, value:'governmental employee or job applicant'},
    {key:9, value:'female governmental employee or job applicant'},
    {key:10, value:'minority governmental employee or job applicant'},
    {key:11, value:'minority female governmental employee or job applicant'},
    {key:12, value:'not listed among agencies in the first Administrative Action variable'},
    {key:13, value:'retired or former governmental employee'},
    {key:14, value:'U.S. House of Representatives'},
    {key:15, value:'interstate compact'},
    {key:16, value:'judge'},
    {key:17, value:'state legislature, house, or committee'},
    {key:18, value:'local governmental unit other than a county, city, town, township, village, or borough'},
    {key:19, value:'governmental official, or an official of an agency established under an interstate compact'},
    {key:20, value:'state or U.S. supreme court'},
    {key:21, value:'local school district or board of education'},
    {key:22, value:'U.S. Senate'},
    {key:23, value:'U.S. senator'},
    {key:24, value:'foreign nation or instrumentality'},
    {key:25, value:'state or local governmental taxpayer, or executor of the estate of'},
    {key:26, value:'state college or university'},
    {key:27, value:'United States'},
    {key:28, value:'State'},
    {key:100, value:'person accused, indicted, or suspected of crime'},
    {key:101, value:'advertising business or agency'},
    {key:102, value:'agent, fiduciary, trustee, or executor'},
    {key:103, value:	'airplane manufacturer, or manufacturer of parts of airplanes'},
    {key:104, value:	'airline'},
    {key:105, value:	'distributor, importer, or exporter of alcoholic beverages'},
    {key:106, value:	'alien, person subject to a denaturalization proceeding, or one whose citizenship is revoked'},
    {key:107, value:	'American Medical Association'},
    {key:108, value:	'National Railroad Passenger Corp.'},
    {key:109, value:	'amusement establishment, or recreational facility'},
    {key:110, value:	'arrested person, or pretrial detainee'},
    {key:111, value:	'attorney, or person acting as such;includes bar applicant or law student, or law firm or bar association'},
    {key:112, value:	'author, copyright holder'},
    {key:113, value:	'bank, savings and loan, credit union, investment company'},
    {key:114, value:	'bankrupt person or business, or business in reorganization'},
    {key:115, value:	'establishment serving liquor by the glass, or package liquor store'},
    {key:116, value:	'water transportation, stevedore'},
    {key:117, value:	'bookstore, newsstand, printer, bindery, purveyor or distributor of books or magazines'},
    {key:118, value:	'brewery, distilleryv'},
    {key:119, value:	'broker, stock exchange, investment or securities firm'},
    {key:120, value:	'construction industry'},
    {key:121, value:	'bus or motorized passenger transportation vehicle'},
    {key:122, value:	'business, corporation'},
    {key:123, value:	'buyer, purchaser'},
    {key:124, value:	'cable TV'},
    {key:125, value:	'car dealer'},
    {key:126, value:	'person convicted of crime'},
    {key:127, value:	'tangible property, other than real estate, including contraband'},
    {key:128, value:	'chemical company'},
    {key:129, value:	'child, children, including adopted or illegitimate'},
    {key:130, value:	'religious organization, institution, or person'},
    {key:131, value:	'private club or facility'},
    {key:132, value:	'coal company or coal mine operator'},
    {key:133, value:	'computer business or manufacturer, hardware or software'},
    {key:134, value:	'consumer, consumer organization'},
    {key:135, value:	'creditor, including institution appearing as such; e.g., a finance company'},
    {key:136, value:	'person allegedly criminally insane or mentally incompetent to stand trial'},
    {key:137, value:	'defendant'},
    {key:138, value:	'debtor'},
    {key:139, value:	'real estate developer'},
    {key:140, value:	'disabled person or disability benefit claimant'},
    {key:141, value:	'distributor'},
    {key:142, value:	'person subject to selective service, including conscientious objector'},
    {key:143, value:	'drug manufacturer'},
    {key:144, value:	'druggist, pharmacist, pharmacy'},
    {key:145, value:	'employee, or job applicant, including beneficiaries of'},
    {key:146, value:	'employer-employee trust agreement, employee health and welfare fund, or multi-employer pension plan'},
    {key:147, value:	'electric equipment manufacturer'},
    {key:148, value:	'electric or hydroelectric power utility, power cooperative, or gas and electric company'},
    {key:149, value:	'eleemosynary institution or person'},
    {key:150, value:	'environmental organization'},
    {key:151, value:	"employer. If employer's relations with employees are governed by the nature of the employer's business (e.g., railroad, boat), rather than labor law generally, the more specific designation is used in place of Employer."},
    {key:152, value:	'farmer, farm worker, or farm organization'},
    {key:153, value:	'father'},
    {key:154, value:	'female employee or job applicant'},
    {key:155, value:	'female'},
    {key:156, value:	'movie, play, pictorial representation, theatrical production, actor, or exhibitor or distributor of'},
    {key:157, value:	'fisherman or fishing company'},
    {key:158, value:	'food, meat packing, or processing company, stockyard'},
    {key:159, value:	'foreign (non-American) nongovernmental entity'},
    {key:160, value:	'franchiser'},
    {key:161, value:	'franchisee'},
    {key:162, value:	'lesbian, gay, bisexual, transexual person or organization'},
    {key:163, value:	"person who guarantees another's obligations"},
    {key:164, value:	'handicapped individual, or organization of devoted to'},
    {key:165, value:	'health organization or person, nursing home, medical clinic or laboratory, chiropractor'},
    {key:166, value:	'heir, or beneficiary, or person so claiming to be'},
    {key:167, value:	'hospital, medical center'},
    {key:168, value:	'husband, or ex-husband'},
    {key:169, value:	'involuntarily committed mental patient'},
    {key:170, value:	'Indian, including Indian tribe or nation'},
    {key:171, value:	'insurance company, or surety'},
    {key:172, value:	'inventor, patent assigner, trademark owner or holder'},
    {key:173, value:	'investor'},
    {key:174, value:	'injured person or legal entity, nonphysically and non-employment related'},
    {key:175, value:	'juvenile'},
    {key:176, value:	'government contractor'},
    {key:177, value:	'holder of a license or permit, or applicant therefore'},
    {key:178, value:	'magazine'},
    {key:179, value:	'male'},
    {key:180, value:	'medical or Medicaid claimant'},
    {key:181, value:	'medical supply or manufacturing co.'},
    {key:182, value:	'racial or ethnic minority employee or job applicant'},
    {key:183, value:	'minority female employee or job applicant'},
    {key:184, value:	'manufacturer'},
    {key:185, value:	'management, executive officer, or director, of business entity'},
    {key:186, value:	'military personnel, or dependent of, including reservist'},
    {key:187, value:	'mining company or miner, excluding coal, oil, or pipeline company'},
    {key:188, value:	'mother'},
    {key:189, value:	'auto manufacturer'},
    {key:190, value:	'newspaper, newsletter, journal of opinion, news service'},
    {key:191, value:	'radio and television network, except cable tv'},
    {key:192, value:	'nonprofit organization or business'},
    {key:193, value:	'nonresident'},
    {key:194, value:	'nuclear power plant or facility'},
    {key:195, value:	'owner, landlord, or claimant to ownership, fee interest, or possession of land as well as chattels'},
    {key:196, value:	'shareholders to whom a tender offer is made'},
    {key:197, value:	'tender offer'},
    {key:198, value:	'oil company, or natural gas producer'},
    {key:199, value:	'elderly person, or organization dedicated to the elderly'},
    {key:200, value:	'out of state noncriminal defendant'},
    {key:201, value:	'political action committee'},
    {key:202, value:	'parent or parents'},
    {key:203, value:	'parking lot or service'},
    {key:204, value:	'patient of a health professional'},
    {key:205, value:	'telephone, telecommunications, or telegraph company'},
    {key:206, value:	'physician, MD or DO, dentist, or medical society'},
    {key:207, value:	'public interest organization'},
    {key:208, value:	'physically injured person, including wrongful death, who is not an employee'},
    {key:209, value:	'pipe line company'},
    {key:210, value:	'package, luggage, container'},
    {key:211, value:	'political candidate, activist, committee, party, party member, organization, or elected official'},
    {key:212, value:	'indigent, needy, welfare recipient'},
    {key:213, value:	'indigent defendant'},
    {key:214, value:	'private person'},
    {key:215, value:	'prisoner, inmate of penal institution'},
    {key:216, value:	'professional organization, business, or person'},
    {key:217, value:	'probationer, or parolee'},
    {key:218, value:	'protester, demonstrator, picketer or pamphleteer (non-employment related), or non-indigent loiterer'},
    {key:219, value:	'public utility'},
    {key:220, value:	'publisher, publishing company'},
    {key:221, value:	'radio station'},
    {key:222, value:	'racial or ethnic minority'},
    {key:223, value:	'person or organization protesting racial or ethnic segregation or discrimination'},
    {key:224, value:	'racial or ethnic minority student or applicant for admission to an educational institution'},
    {key:225, value:	'realtor'},
    {key:226, value:	'journalist, columnist, member of the news media'},
    {key:227, value:	'resident'},
    {key:228, value:	'restaurant, food vendor'},
    {key:229, value:	'retarded person, or mental incompetent'},
    {key:230, value:	'retired or former employee'},
    {key:231, value:	'railroad'},
    {key:232, value:	'private school, college, or university'},
    {key:233, value:	'seller or vendor'},
    {key:234, value:	'shipper, including importer and exporter'},
    {key:235, value:	'shopping center, mall'},
    {key:236, value:	'spouse, or former spouse'},
    {key:237, value:	'stockholder, shareholder, or bondholder'},
    {key:238, value:	'retail business or outlet'},
    {key:239, value:	'student, or applicant for admission to an educational institution'},
    {key:240, value:	"taxpayer or executor of taxpayer's estate, federal only"},
    {key:241, value:	'tenant or lessee'},
    {key:242, value:	'theater, studio'},
    {key:243, value:	'forest products, lumber, or logging company'},
    {key:244, value:	'person traveling or wishing to travel abroad, or overseas travel agent'},
    {key:245, value:	'trucking company, or motor carrier'},
    {key:246, value:	'television station'},
    {key:247, value:	'union member'},
    {key:248, value:	'unemployed person or unemployment compensation applicant or claimant'},
    {key:249, value:	'union, labor organization, or official of'},
    {key:250, value:	'veteran'},
    {key:251, value:	'voter, prospective voter, elector, or a nonelective official seeking reapportionment or redistricting of legislative districts (POL)'},
    {key:252, value:	'wholesale trade'},
    {key:253, value:	'wife, or ex-wife'},
    {key:254, value:	'witness, or person under subpoena'},
    {key:255, value:	'network'},
    {key:256, value:	'slave'},
    {key:257, value:	'slave-owner'},
    {key:258, value:	'bank of the united states'},
    {key:259, value:	'timber company'},
    {key:260, value:	'u.s. job applicants or employees'},
    {key:301, value:	'Army and Air Force Exchange Service'},
    {key:302, value:	'Atomic Energy Commission'},
    {key:303, value:	'Secretary or administrative unit or personnel of the U.S. Air Force'},
    {key:304, value:	'Department or Secretary of Agriculture'},
    {key:305, value:	'Alien Property Custodian'},
    {key:306, value:	'Secretary or administrative unit or personnel of the U.S. Army'},
    {key:307, value:	'Board of Immigration Appeals'},
    {key:308, value:	'Bureau of Indian Affairs'},
    {key:310, value:	'Bonneville Power Administration'},
    {key:311, value:	'Benefits Review Board'},
    {key:312, value:	'Civil Aeronautics Board'},
    {key:313, value:	'Bureau of the Census'},
    {key:314, value:	'Central Intelligence Agency'},
    {key:315, value:	'Commodity Futures Trading Commission'},
    {key:316, value:	'Department or Secretary of Commerce'},
    {key:317, value:	'Comptroller of Currency'},
    {key:318, value:	'Consumer Product Safety Commission'},
    {key:319, value:	'Civil Rights Commission'},
    {key:320, value:	'Civil Service Commission, U.S.'},
    {key:321, value:	'Customs Service or Commissioner of Customs'},
    {key:322, value:	'Defense Base Closure and REalignment Commission'},
    {key:323, value:	'Drug Enforcement Agency'},
    {key:324, value:	'Department or Secretary of Defense (and Department or Secretary of War)'},
    {key:325, value:	'Department or Secretary of Energy'},
    {key:326, value:	'Department or Secretary of the Interior'},
    {key:327, value:	'Department of Justice or Attorney General'},
    {key:328, value:	'Department or Secretary of State'},
    {key:329, value:	'Department or Secretary of Transportation'},
    {key:330, value:	'Department or Secretary of Education'},
    {key:331, value:	"U.S. Employees' Compensation Commission, or Commissioner"},
    {key:332, value:	'Equal Employment Opportunity Commission'},
    {key:333, value:	'Environmental Protection Agency or Administrator'},
    {key:334, value:	'Federal Aviation Agency or Administration'},
    {key:335, value:	'Federal Bureau of Investigation or Director'},
    {key:336, value:	'Federal Bureau of Prisons'},
    {key:337, value:	'Farm Credit Administration'},
    {key:338, value:	'Federal Communications Commission (including a predecessor, Federal Radio Commission)'},
    {key:339, value:	'Federal Credit Union Administration'},
    {key:340, value:	'Food and Drug Administration'},
    {key:341, value:	'Federal Deposit Insurance Corporation'},
    {key:342, value:	'Federal Energy Administration'},
    {key:343, value:	'Federal Election Commission'},
    {key:344, value:	'Federal Energy Regulatory Commission'},
    {key:345, value:	'Federal Housing Administration'},
    {key:346, value:	'Federal Home Loan Bank Board'},
    {key:347, value:	'Federal Labor Relations Authority'},
    {key:348, value:	'Federal Maritime Board'},
    {key:349, value:	'Federal Maritime Commission'},
    {key:350, value:	'Farmers Home Administration'},
    {key:351, value:	'Federal Parole Board'},
    {key:352, value:	'Federal Power Commission'},
    {key:353, value:	'Federal Railroad Administration'},
    {key:354, value:	'Federal Reserve Board of Governors'},
    {key:355, value:	'Federal Reserve System'},
    {key:356, value:	'Federal Savings and Loan Insurance Corporation'},
    {key:357, value:	'Federal Trade Commission'},
    {key:358, value:	'Federal Works Administration, or Administrator'},
    {key:359, value:	'General Accounting Office'},
    {key:360, value:	'Comptroller General'},
    {key:361, value:	'General Services Administration'},
    {key:362, value:	'Department or Secretary of Health, Education and Welfare'},
    {key:363, value:	'Department or Secretary of Health and Human Services'},
    {key:364, value:	'Department or Secretary of Housing and Urban Development'},
    {key:366, value:	'Interstate Commerce Commission'},
    {key:367, value:	'Indian Claims Commission'},
    {key:368, value:	'Immigration and Naturalization Service, or Director of, or District Director of, or Immigration and Naturalization Enforcement'},
    {key:369, value:	'Internal Revenue Service, Collector, Commissioner, or District Director of'},
    {key:370, value:	'Information Security Oversight Office'},
    {key:371, value:	'Department or Secretary of Labor'},
    {key:372, value:	'Loyalty Review Board'},
    {key:373, value:	'Legal Services Corporation'},
    {key:374, value:	'Merit Systems Protection Board'},
    {key:375, value:	'Multistate Tax Commission'},
    {key:376, value:	'National Aeronautics and Space Administration'},
    {key:377, value:	'Secretary or administrative unit of the U.S. Navy'},
    {key:378, value:	'National Credit Union Administration'},
    {key:379, value:	'National Endowment for the Arts'},
    {key:380, value:	'National Enforcement Commission'},
    {key:381, value:	'National Highway Traffic Safety Administration'},
    {key:382, value:	'National Labor Relations Board, or regional office or officer'},
    {key:383, value:	'National Mediation Board'},
    {key:384, value:	'National Railroad Adjustment Board'},
    {key:385, value:	'Nuclear Regulatory Commission'},
    {key:386, value:	'National Security Agency'},
    {key:387, value:	'Office of Economic Opportunity'},
    {key:388, value:	'Office of Management and Budget'},
    {key:389, value:	'Office of Price Administration, or Price Administrator'},
    {key:390, value:	'Office of Personnel Management'},
    {key:391, value:	'Occupational Safety and Health Administration'},
    {key:392, value:	'Occupational Safety and Health Review Commission'},
    {key:393, value:	"Office of Workers' Compensation Programs"},
    {key:394, value:	'Patent Office, or Commissioner of, or Board of Appeals of'},
    {key:395, value:	'Pay Board (established under the Economic Stabilization Act of 1970)'},
    {key:396, value:	'Pension Benefit Guaranty Corporation'},
    {key:397, value:	'U.S. Public Health Service'},
    {key:398, value:	'Postal Rate Commission'},
    {key:399, value:	'Provider Reimbursement Review Board'},
    {key:400, value:	'Renegotiation Board'},
    {key:401, value:	'Railroad Adjustment Board'},
    {key:402, value:	'Railroad Retirement Board'},
    {key:403, value:	'Subversive Activities Control Board'},
    {key:404, value:	'Small Business Administration'},
    {key:405, value:	'Securities and Exchange Commission'},
    {key:406, value:	'Social Security Administration or Commissioner'},
    {key:407, value:	'Selective Service System'},
    {key:408, value:	'Department or Secretary of the Treasury'},
    {key:409, value:	'Tennessee Valley Authority'},
    {key:410, value:	'United States Forest Service'},
    {key:411, value:	'United States Parole Commission'},
    {key:412, value:	'Postal Service and Post Office, or Postmaster General, or Postmaster'},
    {key:413, value:	'United States Sentencing Commission'},
    {key:414, value:	"Veterans' Administration"},
    {key:415, value:	'War Production Board'},
    {key:416, value:	'Wage Stabilization Board'},
    {key:417, value:	'General Land Office of Commissioners'},
    {key:418, value:	'Transportation Security Administration'},
    {key:419, value:	'Surface Transportation Board'},
    {key:420, value:	'U.S. Shipping Board Emergency Fleet Corp.'},
    {key:421, value:	'Reconstruction Finance Corp.'},
    {key:422, value:	'Department or Secretary of Homeland Security'},
    {key:501, value:	'Unidentifiable'},
    {key:600, value:	'International Entity'}
]

const caseOriginKey = [
    {key: 0, value: 'select...'},
    {key: 1, value: 'U.S. Court of Customs and Patent Appeals'},
    {key: 2, value: 'U.S. Court of International Trade'},
    {key: 3, value: 'U.S. Court of Claims, Court of Federal Claims'},
    {key: 4, value: 'U.S. Court of Military Appeals, renamed as Court of Appeals for the Armed Forces'},
    {key: 5, value: 'U.S. Court of Military Review'},
    {key: 6, value: 'U.S. Court of Veterans Appeals'},
    {key: 7, value: 'U.S. Customs Court'},
    {key: 8, value: 'U.S. Court of Appeals, Federal Circuit'},
    {key: 9, value: 'U.S. Tax Court'},
    {key: 10, value: 'Temporary Emergency U.S. Court of Appeals'},
    {key: 12, value: 'U.S. Court for China'},
    {key: 13, value: 'U.S. Consular Courts'},
    {key: 14, value: 'U.S. Commerce Court'},
    {key: 15, value: 'Territorial Supreme Court'},
    {key: 16, value: 'Territorial Appellate Court'},
    {key: 17, value: 'Territorial Trial Court'},
    {key: 18, value: 'Emergency Court of Appeals'},
    {key: 19, value: 'Supreme Court of the District of Columbia'},
    {key: 20, value: 'Bankruptcy Court'},
    {key: 21, value: 'U.S. Court of Appeals, First Circuit'},
    {key: 22, value: 'U.S. Court of Appeals, Second Circuit'},
    {key: 23, value: 'U.S. Court of Appeals, Third Circuit'},
    {key: 24, value: 'U.S. Court of Appeals, Fourth Circuit'},
    {key: 25, value: 'U.S. Court of Appeals, Fifth Circuit'},
    {key: 26, value: 'U.S. Court of Appeals, Sixth Circuit'},
    {key: 27, value: 'U.S. Court of Appeals, Seventh Circuit'},
    {key: 28, value: 'U.S. Court of Appeals, Eighth Circuit'},
    {key: 29, value: 'U.S. Court of Appeals, Ninth Circuit'},
    {key: 30, value: 'U.S. Court of Appeals, Tenth Circuit'},
    {key: 31, value: 'U.S. Court of Appeals, Eleventh Circuit'},
    {key: 32, value: 'U.S. Court of Appeals, District of Columbia Circuit (includes the Court of Appeals for the District of Columbia but not the District of Columbia Court of Appeals, which has local jurisdiction)'},
    {key: 41, value: 'Alabama Middle U.S. District Court'},
    {key: 42, value: 'Alabama Northern U.S. District Court'},
    {key: 43, value: 'Alabama Southern U.S. District Court'},
    {key: 44, value: 'Alaska U.S. District Court'},
    {key: 45, value: 'Arizona U.S. District Court'},
    {key: 46, value: 'Arkansas Eastern U.S. District Court'},
    {key: 47, value: 'Arkansas Western U.S. District Court'},
    {key: 48, value: 'California Central U.S. District Court'},
    {key: 49, value: 'California Eastern U.S. District Court'},
    {key: 50, value: 'California Northern U.S. District Court'},
    {key: 51, value: 'California Southern U.S. District Court'},
    {key: 52, value: 'Colorado U.S. District Court'},
    {key: 53, value: 'Connecticut U.S. District Court'},
    {key: 54, value: 'Delaware U.S. District Court'},
    {key: 55, value: 'District Of Columbia U.S. District Court'},
    {key: 56, value: 'Florida Middle U.S. District Court'},
    {key: 57, value: 'Florida Northern U.S. District Court'},
    {key: 58, value: 'Florida Southern U.S. District Court'},
    {key: 59, value: 'Georgia Middle U.S. District Court'},
    {key: 60, value: 'Georgia Northern U.S. District Court'},
    {key: 61, value: 'Georgia Southern U.S. District Court'},
    {key: 62, value: 'Guam U.S. District Court'},
    {key: 63, value: 'Hawaii U.S. District Court'},
    {key: 64, value: 'Idaho U.S. District Court'},
    {key: 65, value: 'Illinois Central U.S. District Court'},
    {key: 66, value: 'Illinois Northern U.S. District Court'},
    {key: 67, value: 'Illinois Southern U.S. District Court'},
    {key: 68, value: 'Indiana Northern U.S. District Court'},
    {key: 69, value: 'Indiana Southern U.S. District Court'},
    {key: 70, value: 'Iowa Northern U.S. District Court'},
    {key: 71, value: 'Iowa Southern U.S. District Court'},
    {key: 72, value: 'Kansas U.S. District Court'},
    {key: 73, value: 'Kentucky Eastern U.S. District Court'},
    {key: 74, value: 'Kentucky Western U.S. District Court'},
    {key: 75, value: 'Louisiana Eastern U.S. District Court'},
    {key: 76, value: 'Louisiana Middle U.S. District Court'},
    {key: 77, value: 'Louisiana Western U.S. District Court'},
    {key: 78, value: 'Maine U.S. District Court'},
    {key: 79, value: 'Maryland U.S. District Court'},
    {key: 80, value: 'Massachusetts U.S. District Court'},
    {key: 81, value: 'Michigan Eastern U.S. District Court'},
    {key: 82, value: 'Michigan Western U.S. District Court'},
    {key: 83, value: 'Minnesota U.S. District Court'},
    {key: 84, value: 'Mississippi Northern U.S. District Court'},
    {key: 85, value: 'Mississippi Southern U.S. District Court'},
    {key: 86, value: 'Missouri Eastern U.S. District Court'},
    {key: 87, value: 'Missouri Western U.S. District Court'},
    {key: 88, value: 'Montana U.S. District Court'},
    {key: 89, value: 'Nebraska U.S. District Court'},
    {key: 90, value: 'Nevada U.S. District Court'},
    {key: 91, value: 'New Hampshire U.S. District Court'},
    {key: 92, value: 'New Jersey U.S. District Court'},
    {key: 93, value: 'New Mexico U.S. District Court'},
    {key: 94, value: 'New York Eastern U.S. District Court'},
    {key: 95, value: 'New York Northern U.S. District Court'},
    {key: 96, value: 'New York Southern U.S. District Court'},
    {key: 97, value: 'New York Western U.S. District Court'},
    {key: 98, value: 'North Carolina Eastern U.S. District Court'},
    {key: 99, value: 'North Carolina Middle U.S. District Court'},
    {key: 100, value: 'North Carolina Western U.S. District Court'},
    {key: 101, value: 'North Dakota U.S. District Court'},
    {key: 102, value: 'Northern Mariana Islands U.S. District Court'},
    {key: 103, value: 'Ohio Northern U.S. District Court'},
    {key: 104, value: 'Ohio Southern U.S. District Court'},
    {key: 105, value: 'Oklahoma Eastern U.S. District Court'},
    {key: 106, value: 'Oklahoma Northern U.S. District Court'},
    {key: 107, value: 'Oklahoma Western U.S. District Court'},
    {key: 108, value: 'Oregon U.S. District Court'},
    {key: 109, value: 'Pennsylvania Eastern U.S. District Court'},
    {key: 110, value: 'Pennsylvania Middle U.S. District Court'},
    {key: 111, value: 'Pennsylvania Western U.S. District Court'},
    {key: 112, value: 'Puerto Rico U.S. District Court'},
    {key: 113, value: 'Rhode Island U.S. District Court'},
    {key: 114, value: 'South Carolina U.S. District Court'},
    {key: 115, value: 'South Dakota U.S. District Court'},
    {key: 116, value: 'Tennessee Eastern U.S. District Court'},
    {key: 117, value: 'Tennessee Middle U.S. District Court'},
    {key: 118, value: 'Tennessee Western U.S. District Court'},
    {key: 119, value: 'Texas Eastern U.S. District Court'},
    {key: 120, value: 'Texas Northern U.S. District Court'},
    {key: 121, value: 'Texas Southern U.S. District Court'},
    {key: 122, value: 'Texas Western U.S. District Court'},
    {key: 123, value: 'Utah U.S. District Court'},
    {key: 124, value: 'Vermont U.S. District Court'},
    {key: 125, value: 'Virgin Islands U.S. District Court'},
    {key: 126, value: 'Virginia Eastern U.S. District Court'},
    {key: 127, value: 'Virginia Western U.S. District Court'},
    {key: 128, value: 'Washington Eastern U.S. District Court'},
    {key: 129, value: 'Washington Western U.S. District Court'},
    {key: 130, value: 'West Virginia Northern U.S. District Court'},
    {key: 131, value: 'West Virginia Southern U.S. District Court'},
    {key: 132, value: 'Wisconsin Eastern U.S. District Court'},
    {key: 133, value: 'Wisconsin Western U.S. District Court'},
    {key: 134, value: 'Wyoming U.S. District Court'},
    {key: 150, value: 'Louisiana U.S. District Court'},
    {key: 151, value: 'Washington U.S. District Court'},
    {key: 152, value: 'West Virginia U.S. District Court'},
    {key: 153, value: 'Illinois Eastern U.S. District Court'},
    {key: 155, value: 'South Carolina Eastern U.S. District Court'},
    {key: 160, value: 'South Carolina Western U.S. District Court'},
    {key: 162, value: 'Alabama U.S. District Court'},
    {key: 163, value: 'U.S. District Court for the Canal Zone'},
    {key: 164, value: 'Georgia U.S. District Court'},
    {key: 165, value: 'Illinois U.S. District Court'},
    {key: 166, value: 'Indiana U.S. District Court'},
    {key: 167, value: 'Iowa U.S. District Court'},
    {key: 168, value: 'Michigan U.S. District Court'},
    {key: 169, value: 'Mississippi U.S. District Court'},
    {key: 170, value: 'Missouri U.S. District Court'},
    {key: 171, value: 'New Jersey Eastern U.S. District Court (East Jersey U.S. District Court)'},
    {key: 172, value: 'New Jersey Western U.S. District Court (West Jersey U.S. District Court)'},
    {key: 173, value: 'New York U.S. District Court'},
    {key: 174, value: 'North Carolina U.S. District Court'},
    {key: 175, value: 'Ohio U.S. District Court'},
    {key: 176, value: 'Pennsylvania U.S. District Court'},
    {key: 177, value: 'Tennessee U.S. District Court'},
    {key: 178, value: 'Texas U.S. District Court'},
    {key: 179, value: 'Virginia U.S. District Court'},
    {key: 180, value: 'Norfolk U.S. District Court'},
    {key: 181, value: 'Wisconsin U.S. District Court'},
    {key: 182, value: 'Kentucky U.S. Distrcrict Court'},
    {key: 183, value: 'New Jersey U.S. District Court'},
    {key: 184, value: 'California U.S. District Court'},
    {key: 185, value: 'Florida U.S. District Court'},
    {key: 186, value: 'Arkansas U.S. District Court'},
    {key: 187, value: 'District of Orleans U.S. District Court'},
    {key: 300, value: 'State Supreme Court'},
    {key: 301, value: 'State Appellate Court'},
    {key: 302, value: 'State Trial Court'},
    {key: 400, value: 'Eastern Circuit (of the United States)'},
    {key: 401, value: 'Middle Circuit (of the United States)'},
    {key: 402, value: 'Southern Circuit (of the United States)'},
    {key: 403, value: 'Alabama U.S. Circuit Court for (all) District(s) of Alabama'},
    {key: 404, value: 'Arkansas U.S. Circuit Court for (all) District(s) of Arkansas'},
    {key: 405, value: 'California U.S. Circuit for (all) District(s) of California'},
    {key: 406, value: 'Connecticut U.S. Circuit for the District of Connecticut'},
    {key: 407, value: 'Delaware U.S. Circuit for the District of Delaware'},
    {key: 408, value: 'Florida U.S. Circuit for (all) District(s) of Florida'},
    {key: 409, value: 'Georgia U.S. Circuit for (all) District(s) of Georgia'},
    {key: 410, value: 'Illinois U.S. Circuit for (all) District(s) of Illinois'},
    {key: 411, value: 'Indiana U.S. Circuit for (all) District(s) of Indiana'},
    {key: 412, value: 'Iowa U.S. Circuit for (all) District(s) of Iowa'},
    {key: 413, value: 'Kansas U.S. Circuit for the District of Kansas'},
    {key: 414, value: 'Kentucky U.S. Circuit for (all) District(s) of Kentucky'},
    {key: 415, value: 'Louisiana U.S. Circuit for (all) District(s) of Louisiana'},
    {key: 416, value: 'Maine U.S. Circuit for the District of Maine'},
    {key: 417, value: 'Maryland U.S. Circuit for the District of Maryland'},
    {key: 418, value: 'Massachusetts U.S. Circuit for the District of Massachusetts'},
    {key: 419, value: 'Michigan U.S. Circuit for (all) District(s) of Michigan'},
    {key: 420, value: 'Minnesota U.S. Circuit for the District of Minnesota'},
    {key: 421, value: 'Mississippi U.S. Circuit for (all) District(s) of Mississippi'},
    {key: 422, value: 'Missouri U.S. Circuit for (all) District(s) of Missouri'},
    {key: 423, value: 'Nevada U.S. Circuit for the District of Nevada'},
    {key: 424, value: 'New Hampshire U.S. Circuit for the District of New Hampshire'},
    {key: 425, value: 'New Jersey U.S. Circuit for (all) District(s) of New Jersey'},
    {key: 426, value: 'New York U.S. Circuit for (all) District(s) of New York'},
    {key: 427, value: 'North Carolina U.S. Circuit for (all) District(s) of North Carolina'},
    {key: 428, value: 'Ohio U.S. Circuit for (all) District(s) of Ohio'},
    {key: 429, value: 'Oregon U.S. Circuit for the District of Oregon'},
    {key: 430, value: 'Pennsylvania U.S. Circuit for (all) District(s) of Pennsylvania'},
    {key: 431, value: 'Rhode Island U.S. Circuit for the District of Rhode Island'},
    {key: 432, value: 'South Carolina U.S. Circuit for the District of South Carolina'},
    {key: 433, value: 'Tennessee U.S. Circuit for (all) District(s) of Tennessee'},
    {key: 434, value: 'Texas U.S. Circuit for (all) District(s) of Texas'},
    {key: 435, value: 'Vermont U.S. Circuit for the District of Vermont'},
    {key: 436, value: 'Virginia U.S. Circuit for (all) District(s) of Virginia'},
    {key: 437, value: 'West Virginia U.S. Circuit for (all) District(s) of West Virginia'},
    {key: 438, value: 'Wisconsin U.S. Circuit for (all) District(s) of Wisconsin'},
    {key: 439, value: 'Wyoming U.S. Circuit for the District of Wyoming'},
    {key: 440, value: 'Circuit Court of the District of Columbia'},
    {key: 441, value: 'Nebraska U.S. Circuit for the District of Nebraska'},
    {key: 442, value: 'Colorado U.S. Circuit for the District of Colorado'},
    {key: 443, value: 'Washington U.S. Circuit for (all) District(s) of Washington'},
    {key: 444, value: 'Idaho U.S. Circuit Court for (all) District(s) of Idaho'},
    {key: 445, value: 'Montana U.S. Circuit Court for (all) District(s) of Montana'},
    {key: 446, value: 'Utah U.S. Circuit Court for (all) District(s) of Utah'},
    {key: 447, value: 'South Dakota U.S. Circuit Court for (all) District(s) of South Dakota'},
    {key: 448, value: 'North Dakota U.S. Circuit Court for (all) District(s) of North Dakota'},
    {key: 449, value: 'Oklahoma U.S. Circuit Court for (all) District(s) of Oklahoma'},
    {key: 601, value: 'Court of Private Land Claims'},
]

const issueKey = [
    {key: 0, value: 'select...'},
    {key: 10010, value: 'involuntary confession'},
    {key: 10020, value: 'habeas corpus'},
    {key: 10030, value: 'plea bargaining'},
    {key: 10040, value: 'retroactivity'},
    {key: 10050, value: 'search and seizure (other than as pertains to vehicles or Crime Control Act'},
    {key: 10060, value: 'search and seizure, vehicles'},
    {key: 10070, value: 'search and seizure, Crime Control Act'},
    {key: 10080, value: 'contempt of court or congress'},
    {key: 10090, value: 'self-incrimination (other than Miranda or immunity from prosecution'},
    {key: 10100, value: 'Miranda warnings'},
    {key: 10110, value: 'self-incrimination, immunity from prosecution'},
    {key: 10120, value: 'right to counsel'},
    {key: 10130, value: 'cruel and unusual punishment, death penalty'},
    {key: 10140, value: 'cruel and unusual punishment, no death penalty'},
    {key: 10150, value: 'line-up'},
    {key: 10160, value: 'discovery and inspection'},
    {key: 10170, value: 'double jeopardy'},
    {key: 10180, value: 'ex post facto (state'},
    {key: 10200, value: 'extra-legal jury influences: prejudicial statements or evidence'},
    {key: 10210, value: 'extra-legal jury influences: contact with jurors outside the courtroom'},
    {key: 10220, value: 'extra-legal jury influences: jury instructions'},
    {key: 10230, value: 'extra-legal jury influences: voir dire'},
    {key: 10240, value: 'extra-legal jury influences: prison garb or appearance'},
    {key: 10250, value: 'extra-legal jury influences: jurors and death penalty'},
    {key: 10260, value: 'extra-legal jury influences: pretrial publicity'},
    {key: 10190, value: 'extra-legal jury influences: miscellaneous'},
    {key: 10270, value: 'right to confrontration'},
    {key: 10280, value: 'subconstitutional fair procedure: confession of error'},
    {key: 10290, value: 'subconstitutional fair procedure: conspiracy'},
    {key: 10300, value: 'subconstitutional fair procedure: entrapment'},
    {key: 10310, value: 'subconstitutional fair procedure: exhaustion of remedies'},
    {key: 10320, value: 'subconstitutional fair procedure: fugitive from justice'},
    {key: 10330, value: 'subconstitutional fair procedure: presentation, admissibility, sufficiency of evidence'},
    {key: 10340, value: 'subconstitutional fair procedure: stay of execution'},
    {key: 10350, value: 'subconstitutional fair procedure: timeliness'},
    {key: 10360, value: 'subconstitutional fair procedure: miscellaneous'},
    {key: 10380, value: 'statutory construction of criminal laws: assault'},
    {key: 10390, value: 'statutory construction of criminal laws: bank robbery'},
    {key: 10400, value: 'statutory construction of criminal laws: conspiracy'},
    {key: 10410, value: 'statutory construction of criminal laws: escape from custody'},
    {key: 10420, value: 'statutory construction of criminal laws: false statements'},
    {key: 10430, value: 'statutory construction of criminal laws: financial (other than fraud or internal revenue)'},
    {key: 10440, value: 'statutory construction of criminal laws: firearms'},
    {key: 10450, value: 'statutory construction of criminal laws: fraud'},
    {key: 10460, value: 'statutory construction of criminal laws: gambling'},
    {key: 10470, value: 'statutory construction of criminal laws: Hobbs Act; i.e., 18 USC 1951'},
    {key: 10480, value: 'statutory construction of criminal laws: immigration'},
    {key: 10490, value: 'statutory construction of criminal laws: internal revenue'},
    {key: 10500, value: 'statutory construction of criminal laws: Mann Act and related statutes'},
    {key: 10510, value: 'statutory construction of criminal laws: narcotics includes regulation and prohibition of alcohol'},
    {key: 10520, value: 'statutory construction of criminal laws: obstruction of justice'},
    {key: 10530, value: 'statutory construction of criminal laws: perjury'},
    {key: 10540, value: 'statutory construction of criminal laws: Travel Act, 18 USC 1952'},
    {key: 10550, value: 'statutory construction of criminal laws: war crimes'},
    {key: 10560, value: 'statutory construction of criminal laws: sentencing guidelines'},
    {key: 10570, value: 'statutory construction of criminal laws: miscellaneous'},
    {key: 10370, value: 'Federal Rules of Criminal Procedure'},
    {key: 10580, value: 'right to jury trial'},
    {key: 10590, value: 'right to speedy trial'},
    {key: 10600, value: 'miscellaneous criminal procedure'},
    {key: 20010, value: 'voting'},
    {key: 20020, value: 'Voting Rights Act 1965'},
    {key: 20030, value: 'ballot access'},
    {key: 20050, value: 'desegregation, schools'},
    {key: 20060, value: 'employment discrimination: race, age, religion, illegitimacy, national origin, or working conditions'},
    {key: 20070, value: 'affirmative action'},
    {key: 20040, value: 'desegregation: other than school, employement or affirmative action'},
    {key: 20075, value: 'slavery or indenture'},
    {key: 20080, value: 'sit-in demonstrations'},
    {key: 20090, value: 'reapportionment: other than by the Voting Rights Act'},
    {key: 20100, value: "debtors' rights"},
    {key: 20110, value: 'deportation'},
    {key: 20120, value: 'employability of aliens'},
    {key: 20130, value: 'sex discrimination (excluding employment)'},
    {key: 20140, value: 'sex discrimination in employment'},
    {key: 20150, value: 'Indians (other than state jurisdiction)'},
    {key: 20160, value: 'state jurisdiction over Indians'},
    {key: 20170, value: 'juveniles'},
    {key: 20180, value: 'poverty law, constitutional'},
    {key: 20190, value: 'poverty law, statutory: welfare benefits'},
    {key: 20200, value: 'rights of illegitimates'},
    {key: 20210, value: 'rights of handicappped'},
    {key: 20220, value: 'residency requirements'},
    {key: 20230, value: 'military: draftee, or subject to induction'},
    {key: 20240, value: 'military: active duty'},
    {key: 20250, value: 'military: veteran'},
    {key: 20260, value: 'immigration and naturalization: permanent residence'},
    {key: 20270, value: 'immigration and naturalization: citizenship'},
    {key: 20280, value: 'immigration and naturalization: loss of citizenship, denaturalisation'},
    {key: 20290, value: 'immigration and naturalization: access to public education'},
    {key: 20300, value: 'immigration and naturalization: welfare benefits'},
    {key: 20310, value: 'immigration and naturalization: miscellaneous'},
    {key: 20320, value: 'indigents: appointment of counsel'},
    {key: 20330, value: 'indigents: inadequate representation by counsel'},
    {key: 20340, value: 'indigents: payment of fine'},
    {key: 20350, value: 'indigents: costs or filing fees'},
    {key: 20360, value: 'indigents: U.S. Supreme Court docketing fee'},
    {key: 20370, value: 'indigents: transcript'},
    {key: 20380, value: 'indigents: assistance of psychiatrist'},
    {key: 20390, value: 'indigents: miscellaneous'},
    {key: 20400, value: 'liability, civil rights act'},
    {key: 20410, value: 'miscellaneous civil rights'},
    {key: 30010, value: 'First Amendment, miscellaneous'},
    {key: 30020, value: 'commercial speech, exlcuding attorneys'},
    {key: 60020, value: 'commercial speech, attorneys'},
    {key: 30030, value: 'libel: defamation'},
    {key: 30040, value: 'libel: privacy'},
    {key: 30050, value: 'legislative investigations: internal security'},
    {key: 30060, value: 'federal or state internal security legislation: Smith, Internal Security, and related federal statutes'},
    {key: 30070, value: 'loyalty oath or non-Communist affidavit'},
    {key: 30080, value: 'loyalty oath: bar applicants'},
    {key: 30090, value: 'loyalty oath: government employees'},
    {key: 30100, value: 'loyalty oath: political party'},
    {key: 30110, value: 'loyalty oath: teachers'},
    {key: 30120, value: 'security risks: denial of benefits or dismissal of employees for reasons other than failure to meet loyalty oath'},
    {key: 30130, value: 'conscientious objectors'},
    {key: 30140, value: 'campaign spending'},
    {key: 30150, value: 'protest demonstrations'},
    {key: 30160, value: 'free exercise of religion'},
    {key: 30170, value: 'establishment of religion'},
    {key: 30180, value: 'parochiaid: government aid to religious schools, or religious requirements in public schools'},
    {key: 30190, value: 'obscenity, state'},
    {key: 30200, value: 'obscenity, federal'},
    {key: 40020, value: 'due process: hearing or notice'},
    {key: 40030, value: 'due process: hearing, government employees'},
    {key: 40040, value: "due process: prisoners' rights and defendants' rights"},
    {key: 40050, value: 'due process: impartial decision maker'},
    {key: 40060, value: 'due process: jurisdiction'},
    {key: 40070, value: 'due process: takings clause'},
    {key: 40010, value: 'due process: miscellaneous'},
    {key: 50010, value: 'privacy'},
    {key: 50020, value: 'abortion: including contraceptives'},
    {key: 50030, value: 'right to die'},
    {key: 50040, value: 'Freedom of Information Act'},
    {key: 60010, value: "attorneys' and governmental employees' or officials' fees or compensation or licenses"},
    {key: 60030, value: 'admission to a state or federal bar, disbarment, and attorney discipline'},
    {key: 60040, value: 'admission to, or disbarment from, Bar of the U.S. Supreme Court'},
    {key: 70010, value: 'arbitration (labor management, employee relations'},
    {key: 70020, value: 'union antitrust'},
    {key: 70030, value: 'union or closed shop'},
    {key: 70040, value: 'Fair Labor Standards Act'},
    {key: 70050, value: 'Occupational Safety and Health Act'},
    {key: 70060, value: 'union-union member dispute'},
    {key: 70070, value: 'labor-management disputes: bargaining'},
    {key: 70080, value: 'labor-management disputes: employee discharge'},
    {key: 70090, value: 'labor-management disputes: distribution of union literature'},
    {key: 70100, value: 'labor-management disputes: representative election'},
    {key: 70110, value: 'labor-management disputes: antistrike injunction'},
    {key: 70120, value: 'labor-management disputes: jurisdictional dispute'},
    {key: 70130, value: 'labor-management disputes: right to organize'},
    {key: 70140, value: 'labor-management disputes: picketing'},
    {key: 70150, value: 'labor-management disputes: secondary activity'},
    {key: 70160, value: 'labor-management disputes: no-strike clause'},
    {key: 70170, value: 'labor-management disputes: union representatives'},
    {key: 70180, value: 'labor-management disputes: union trust funds'},
    {key: 70190, value: 'labor-management disputes: working conditions'},
    {key: 70200, value: 'labor-management disputes: miscellaneous dispute'},
    {key: 70210, value: 'miscellaneous union'},
    {key: 80010, value: 'antitrust'},
    {key: 80020, value: 'mergers'},
    {key: 80030, value: 'bankruptcy'},
    {key: 80040, value: 'sufficiency of evidence: jury determinatino of compensation for injury or death'},
    {key: 80050, value: 'election of remedies: injured persons or things'},
    {key: 80060, value: 'liability, governmental: tort or contract other than defense of criminal actions brought under civil rights'},
    {key: 80080, value: 'liability, punitive'},
    {key: 80070, value: 'liability, other than sufficiency of evidence, election of remedies, or punitive damages'},
    {key: 80090, value: 'Employee Retirement Income Security Act'},
    {key: 80100, value: 'state or local government tax'},
    {key: 80105, value: 'state and territorial land claims'},
    {key: 80110, value: 'state or local government regulation, business'},
    {key: 80120, value: 'federal or state regulation of securities'},
    {key: 80130, value: 'natural resources - environmental protection'},
    {key: 80140, value: 'corruption, governmental regulation'},
    {key: 80150, value: 'zoning: constitutionality or restrictions'},
    {key: 80160, value: 'arbitration'},
    {key: 80170, value: 'federal or state consumer protection'},
    {key: 80180, value: 'patent'},
    {key: 80190, value: 'copyright'},
    {key: 80200, value: 'trademark'},
    {key: 80210, value: 'patentability of computer processes'},
    {key: 80220, value: 'federal or state regulation of transportation regulation: railroad'},
    {key: 80230, value: 'federal and state regulation of transportation: boat'},
    {key: 80240, value: 'federal and state regulation of transportation: truck, or motor carrier'},
    {key: 80250, value: 'federal and state regulation of transportation: pipeline'},
    {key: 80260, value: 'federal and state regulation of transportation: airline'},
    {key: 80270, value: 'federal and state regulation of transportation: electric power'},
    {key: 80280, value: 'federal and state regulation of transportation: nuclear power'},
    {key: 80280, value: 'federal and some few state regulation of public utilities regulation: nuclear power'},
    {key: 80290, value: 'federal and some few state regulation of public utilities regulation: oil producer'},
    {key: 80300, value: 'federal and some few state regulation of public utilities regulation: gas producer'},
    {key: 80310, value: 'federal and some few state regulation of public utilities regulation: gas pipeline'},
    {key: 80320, value: 'federal and some few state regulation of public utilities regulation: radio and television'},
    {key: 80330, value: 'federal and some few state regulation of public utilities regulation: cable television'},
    {key: 80340, value: 'federal and some few state regulations of public utilities regulation: telephone or telegraph company'},
    {key: 80350, value: 'miscellaneous economic regulation'},
    {key: 90010, value: 'comity: civil rights'},
    {key: 90020, value: 'comity: criminal procedure'},
    {key: 90030, value: 'comity: First Amendment'},
    {key: 90040, value: 'comity: habeas corpus'},
    {key: 90050, value: 'comity: military'},
    {key: 90060, value: 'comity: obscenity'},
    {key: 90070, value: 'comity: privacy'},
    {key: 90080, value: 'comity: miscellaneous'},
    {key: 90090, value: 'comity: primarily removal cases, civil procedure'},
    {key: 90100, value: 'assessment of costs or damages: as part of a court order'},
    {key: 90110, value: 'Federal Rules of Civil Procedure including Supreme Court Rules, application of the Federal Rules of Evidence, Federal Rules of Appellate Procedure in civil litigation, Circuit Court Rules, and state rules and admiralty rules'},
    {key: 90120, value: "judicial review of administrative agency's or administrative official's actions and procedures"},
    {key: 90130, value: 'mootness'},
    {key: 90140, value: 'venue'},
    {key: 90150, value: 'no merits: writ improvidently granted'},
    {key: 90160, value: 'no merits: dismissed or affirmed for want of a substantial or properly presented federal question, or a nonsuit'},
    {key: 90170, value: 'no merits: dismissed or affirmed for want of jurisdiction'},
    {key: 90180, value: 'no merits: adequate non-federal grounds for decision'},
    {key: 90190, value: 'no merits: remand to determine basis of state or federal court decision'},
    {key: 90200, value: 'no merits: miscellaneous'},
    {key: 90210, value: 'standing to sue: adversary parties'},
    {key: 90220, value: 'standing to sue: direct injury'},
    {key: 90230, value: 'standing to sue: legal injury'},
    {key: 90240, value: 'standing to sue: personal injury'},
    {key: 90250, value: 'standing to sue: justiciable question'},
    {key: 90260, value: 'standing to sue: live dispute'},
    {key: 90270, value: 'standing to sue: parens patriae standing'},
    {key: 90280, value: 'standing to sue: statutory standing'},
    {key: 90290, value: 'standing to sue: private or implied cause of action'},
    {key: 90300, value: "standing to sue: taxpayer's suit"},
    {key: 90310, value: 'standing to sue: miscellaneous'},
    {key: 90320, value: 'judicial administration: jurisdiction or authority of federal district courts or territorial courts'},
    {key: 90330, value: 'judicial administration: jurisdiction or authority of federal courts of appeals'},
    {key: 90340, value: 'judicial administration: Supreme Court jurisdiction or authority on appeal or writ of error, from federal district courts or courts of appeals'},
    {key: 90350, value: 'judicial administration: Supreme Court jurisdiction or authority on appeal or writ of error, from highest state court'},
    {key: 90360, value: 'judicial administration: jurisdiction or authority of the Court of Claims'},
    {key: 90370, value: "judicial administration: Supreme Court's original jurisdiction"},
    {key: 90380, value: 'judicial administration: review of non-final order'},
    {key: 90390, value: 'judicial administration: change in state law'},
    {key: 90400, value: 'judicial administration: federal question'},
    {key: 90410, value: 'judicial administration: ancillary or pendent jurisdiction'},
    {key: 90420, value: 'judicial administration: extraordinary relief (e.g., mandamus, injunction)'},
    {key: 90430, value: 'judicial administration: certification'},
    {key: 90440, value: 'judicial administration: resolution of circuit conflict, or conflict between or among other courts'},
    {key: 90450, value: 'judicial administration: objection to reason for denial of certiorari or appeal'},
    {key: 90460, value: 'judicial administration: collateral estoppel or res judicata'},
    {key: 90470, value: 'judicial administration: interpleader'},
    {key: 90480, value: 'judicial administration: untimely filing'},
    {key: 90490, value: 'judicial administration: Act of State doctrine'},
    {key: 90500, value: 'judicial administration: miscellaneous'},
    {key: 90510, value: "Supreme Court's certiorari, writ of error, or appeals jurisdiction"},
    {key: 90520, value: 'miscellaneous judicial power, especially diversity jurisdiction'},
    {key: 100010, value: 'federal-state ownership dispute'},
    {key: 100020, value: 'federal pre-emption of state court jurisdiction'},
    {key: 100030, value: 'federal pre-emption of state legislation or regulation'},
    {key: 100040, value: 'Submerged Lands Act'},
    {key: 100050, value: 'national supremacy: commodities'},
    {key: 100060, value: 'national supremacy: intergovernmental tax immunity'},
    {key: 100070, value: 'national supremacy: marital and family relationships and property, including obligation of child support'},
    {key: 100080, value: 'national supremacy: natural resources'},
    {key: 100090, value: 'national supremacy: pollution, air or water'},
    {key: 100100, value: 'national supremacy: public utilities'},
    {key: 100110, value: 'national supremacy: state tax'},
    {key: 100120, value: 'national supremacy: miscellaneous'},
    {key: 100130, value: 'miscellaneous federalism'},
    {key: 110010, value: 'boundary dispute between states'},
    {key: 110020, value: 'non-real property dispute between states'},
    {key: 110030, value: 'miscellaneous interstate relations conflict'},
    {key: 110033, value: 'incorporation of foreign territories'},
    {key: 120010, value: 'federal taxation, typically under provisions of the Internal Revenue Code'},
    {key: 120020, value: 'federal taxation of gifts, personal, business, or professional expenses'},
    {key: 120030, value: 'priority of federal fiscal claims: over those of the states or private entities'},
    {key: 120040, value: 'miscellaneous federal taxation'},
    {key: 130010, value: 'legislative veto'},
    {key: 130015, value: 'executive authority vis-a-vis congress or the states'},
    {key: 130020, value: 'miscellaneous'},
    {key: 140010, value: 'real property'},
    {key: 140020, value: 'personal property'},
    {key: 140030, value: 'contracts'},
    {key: 140040, value: 'evidence'},
    {key: 140050, value: 'civil procedure'},
    {key: 140060, value: 'torts'},
    {key: 140070, value: 'wills and trusts'},
    {key: 140080, value: 'commercial transactions'}
]

module.exports = {
    respondentKey,
    caseOriginKey,
    issueKey
}
